apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsawardwinner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmsawardwinner
  template:
    metadata:
      labels:
        app: bpdmsawardwinner
    spec:
      containers:
        - name: bpdmsawardwinner
          image: cstardacr.azurecr.io/bpdmsawardwinner
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmsawardwinner
            - secretRef:
                name: application-insights
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: bpdmsawardwinner
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20

